// src/app/components/IRInspector.svelte
<script lang="ts">
import type { CharacterDelta, NarrativeIR } from "../../types/index.js";
import { Badge, Button, Pane } from "../primitives/index.js";

let {
  ir,
  sceneTitle,
  isExtracting,
  canExtract,
  onExtract,
  onVerify,
  onUpdate,
  onClose,
}: {
  ir: NarrativeIR | null;
  sceneTitle: string;
  isExtracting: boolean;
  canExtract: boolean;
  onExtract: () => void;
  onVerify: () => void;
  onUpdate: (ir: NarrativeIR) => void;
  onClose: () => void;
} = $props();

function hasDeltaData(delta: CharacterDelta): boolean {
  return !!(delta.learned || delta.suspicionGained || delta.emotionalShift || delta.relationshipChange);
}
</script>

<Pane title="IR Inspector — {sceneTitle}" extraClass="ir-inspector">
  {#snippet headerRight()}
    <div class="pane-actions">
      {#if !ir}
        <Badge>No IR</Badge>
      {:else if ir.verified}
        <Badge variant="accepted">Verified</Badge>
      {:else}
        <Badge variant="warning">Unverified</Badge>
      {/if}
      <Button onclick={onExtract} disabled={!canExtract || isExtracting}>
        {isExtracting ? "Extracting..." : ir ? "Re-extract" : "Extract IR"}
      </Button>
      {#if ir && !ir.verified}
        <Button variant="primary" onclick={onVerify}>Verify</Button>
      {/if}
      <Button onclick={onClose}>✕</Button>
    </div>
  {/snippet}

  {#if !ir}
    <div class="ir-empty">No IR extracted yet. Complete the scene and click "Extract IR" to analyze.</div>
  {:else}
    <div class="ir-body">
      <section>
        <h4 class="ir-heading">Events ({ir.events.length})</h4>
        {#if ir.events.length === 0}
          <p class="ir-none">None recorded</p>
        {:else}
          <ul class="ir-list">{#each ir.events as e, i}<li>{e}</li>{/each}</ul>
        {/if}
      </section>

      <section class="ir-section">
        <h4 class="ir-heading">
          Facts Introduced ({ir.factsIntroduced.length}) •
          <span class="ir-subheading">Revealed to Reader: {ir.factsRevealedToReader.length}</span>
        </h4>
        {#if ir.factsIntroduced.length === 0}
          <p class="ir-none">None</p>
        {:else}
          <ul class="ir-list">{#each ir.factsIntroduced as f, i}<li>{f}</li>{/each}</ul>
        {/if}
      </section>

      <section class="ir-section">
        <h4 class="ir-heading">Character Deltas ({ir.characterDeltas.length})</h4>
        {#if ir.characterDeltas.length === 0}
          <p class="ir-none">No character changes recorded</p>
        {:else}
          {#each ir.characterDeltas as delta, i}
            {#if hasDeltaData(delta)}
              <div class="delta-card">
                <strong class="delta-char">{delta.characterId}</strong>
                {#if delta.learned}<div class="delta-field"><span class="delta-label">LEARNED: </span>{delta.learned}</div>{/if}
                {#if delta.suspicionGained}<div class="delta-field"><span class="delta-label">SUSPECTS: </span>{delta.suspicionGained}</div>{/if}
                {#if delta.emotionalShift}<div class="delta-field"><span class="delta-label">EMOTIONAL: </span>{delta.emotionalShift}</div>{/if}
                {#if delta.relationshipChange}<div class="delta-field"><span class="delta-label">RELATIONSHIP: </span>{delta.relationshipChange}</div>{/if}
              </div>
            {/if}
          {/each}
        {/if}
      </section>

      <section class="ir-section">
        <h4 class="ir-heading">
          Setups Planted <Badge variant={ir.setupsPlanted.length > 0 ? "accepted" : "default"}>{ir.setupsPlanted.length}</Badge>
          {" • "}Payoffs Executed <Badge variant={ir.payoffsExecuted.length > 0 ? "accepted" : "default"}>{ir.payoffsExecuted.length}</Badge>
        </h4>
        {#each ir.setupsPlanted as s, i}<div class="setup-item">↑ {s}</div>{/each}
        {#each ir.payoffsExecuted as p, i}<div class="setup-item">✓ {p}</div>{/each}
      </section>

      {#if ir.unresolvedTensions.length > 0}
        <section class="ir-section">
          <h4 class="ir-heading">Unresolved Tensions ({ir.unresolvedTensions.length})</h4>
          <ul class="ir-list">{#each ir.unresolvedTensions as t, i}<li>{t}</li>{/each}</ul>
        </section>
      {/if}

      {#if ir.factsWithheld.length > 0}
        <section class="ir-section">
          <h4 class="ir-heading">Facts Withheld from Reader ({ir.factsWithheld.length})</h4>
          <ul class="ir-list withheld">{#each ir.factsWithheld as f, i}<li>{f}</li>{/each}</ul>
        </section>
      {/if}
    </div>
  {/if}
</Pane>

<style>
  :global(.ir-inspector) { max-height: 80vh; overflow-y: auto; }
  .ir-empty { padding: 24px; opacity: 0.6; text-align: center; }
  .ir-body { padding: 16px; }
  .ir-heading { margin: 0 0 8px; opacity: 0.7; }
  .ir-subheading { opacity: 0.5; }
  .ir-none { opacity: 0.4; }
  .ir-list { margin: 0; padding-left: 20px; }
  .ir-section { margin-top: 16px; }
  .delta-card { border: 1px solid var(--border-strong); border-radius: var(--radius-md); padding: 8px 12px; margin-bottom: 8px; }
  .delta-char { font-size: 0.85em; opacity: 0.7; }
  .delta-field { margin-top: 4px; }
  .delta-label { opacity: 0.6; font-size: 0.8em; }
  .setup-item { font-size: 0.9em; }
  .withheld li { opacity: 0.6; }
</style>

// src/app/components/IRInspector.tsx
import type { CharacterDelta, NarrativeIR } from "../../types/index.js";

interface Props {
  ir: NarrativeIR | null;
  sceneTitle: string;
  isExtracting: boolean;
  canExtract: boolean;
  onExtract: () => void;
  onVerify: () => void;
  onUpdate: (ir: NarrativeIR) => void;
  onClose: () => void;
}

function IRBadge({ ir }: { ir: NarrativeIR | null }) {
  if (!ir) return <span className="badge">No IR</span>;
  if (ir.verified) return <span className="badge badge-accepted">Verified</span>;
  return <span className="badge badge-warning">Unverified</span>;
}

function DeltaCard({ delta }: { delta: CharacterDelta }) {
  const hasData = delta.learned || delta.suspicionGained || delta.emotionalShift || delta.relationshipChange;
  if (!hasData) return null;

  return (
    <div style={{ border: "1px solid #333", borderRadius: 4, padding: "8px 12px", marginBottom: 8 }}>
      <strong style={{ fontSize: "0.85em", opacity: 0.7 }}>{delta.characterId}</strong>
      {delta.learned && (
        <div style={{ marginTop: 4 }}>
          <span style={{ opacity: 0.6, fontSize: "0.8em" }}>LEARNED: </span>
          {delta.learned}
        </div>
      )}
      {delta.suspicionGained && (
        <div style={{ marginTop: 4 }}>
          <span style={{ opacity: 0.6, fontSize: "0.8em" }}>SUSPECTS: </span>
          {delta.suspicionGained}
        </div>
      )}
      {delta.emotionalShift && (
        <div style={{ marginTop: 4 }}>
          <span style={{ opacity: 0.6, fontSize: "0.8em" }}>EMOTIONAL: </span>
          {delta.emotionalShift}
        </div>
      )}
      {delta.relationshipChange && (
        <div style={{ marginTop: 4 }}>
          <span style={{ opacity: 0.6, fontSize: "0.8em" }}>RELATIONSHIP: </span>
          {delta.relationshipChange}
        </div>
      )}
    </div>
  );
}

export function IRInspector({
  ir,
  sceneTitle,
  isExtracting,
  canExtract,
  onExtract,
  onVerify,
  onUpdate,
  onClose,
}: Props) {
  return (
    <div className="pane" style={{ maxHeight: "80vh", overflowY: "auto" }}>
      <div className="pane-header">
        <span>IR Inspector — {sceneTitle}</span>
        <div className="pane-actions">
          <IRBadge ir={ir} />
          <button onClick={onExtract} disabled={!canExtract || isExtracting}>
            {isExtracting ? "Extracting..." : ir ? "Re-extract" : "Extract IR"}
          </button>
          {ir && !ir.verified && (
            <button className="primary" onClick={onVerify}>
              Verify
            </button>
          )}
          <button onClick={onClose}>✕</button>
        </div>
      </div>

      {!ir && (
        <div style={{ padding: 24, opacity: 0.6, textAlign: "center" }}>
          No IR extracted yet. Complete the scene and click "Extract IR" to analyze.
        </div>
      )}

      {ir && (
        <div style={{ padding: 16 }}>
          {/* Events */}
          <section>
            <h4 style={{ margin: "0 0 8px", opacity: 0.7 }}>Events ({ir.events.length})</h4>
            {ir.events.length === 0 ? (
              <p style={{ opacity: 0.4 }}>None recorded</p>
            ) : (
              <ul style={{ margin: 0, paddingLeft: 20 }}>
                {ir.events.map((e, i) => (
                  <li key={i}>{e}</li>
                ))}
              </ul>
            )}
          </section>

          {/* Facts Introduced */}
          <section style={{ marginTop: 16 }}>
            <h4 style={{ margin: "0 0 8px", opacity: 0.7 }}>
              Facts Introduced ({ir.factsIntroduced.length}) •{" "}
              <span style={{ opacity: 0.5 }}>Revealed to Reader: {ir.factsRevealedToReader.length}</span>
            </h4>
            {ir.factsIntroduced.length === 0 ? (
              <p style={{ opacity: 0.4 }}>None</p>
            ) : (
              <ul style={{ margin: 0, paddingLeft: 20 }}>
                {ir.factsIntroduced.map((f, i) => (
                  <li key={i}>{f}</li>
                ))}
              </ul>
            )}
          </section>

          {/* Character Deltas */}
          <section style={{ marginTop: 16 }}>
            <h4 style={{ margin: "0 0 8px", opacity: 0.7 }}>Character Deltas ({ir.characterDeltas.length})</h4>
            {ir.characterDeltas.length === 0 ? (
              <p style={{ opacity: 0.4 }}>No character changes recorded</p>
            ) : (
              ir.characterDeltas.map((d, i) => <DeltaCard key={i} delta={d} />)
            )}
          </section>

          {/* Setups / Payoffs */}
          <section style={{ marginTop: 16 }}>
            <h4 style={{ margin: "0 0 8px", opacity: 0.7 }}>
              Setups Planted{" "}
              <span className={`badge ${ir.setupsPlanted.length > 0 ? "badge-accepted" : ""}`}>
                {ir.setupsPlanted.length}
              </span>
              {" • "}
              Payoffs Executed{" "}
              <span className={`badge ${ir.payoffsExecuted.length > 0 ? "badge-accepted" : ""}`}>
                {ir.payoffsExecuted.length}
              </span>
            </h4>
            {ir.setupsPlanted.map((s, i) => (
              <div key={i} style={{ fontSize: "0.9em" }}>
                ↑ {s}
              </div>
            ))}
            {ir.payoffsExecuted.map((p, i) => (
              <div key={i} style={{ fontSize: "0.9em" }}>
                ✓ {p}
              </div>
            ))}
          </section>

          {/* Unresolved Tensions */}
          {ir.unresolvedTensions.length > 0 && (
            <section style={{ marginTop: 16 }}>
              <h4 style={{ margin: "0 0 8px", opacity: 0.7 }}>Unresolved Tensions ({ir.unresolvedTensions.length})</h4>
              <ul style={{ margin: 0, paddingLeft: 20 }}>
                {ir.unresolvedTensions.map((t, i) => (
                  <li key={i}>{t}</li>
                ))}
              </ul>
            </section>
          )}

          {/* Facts Withheld */}
          {ir.factsWithheld.length > 0 && (
            <section style={{ marginTop: 16 }}>
              <h4 style={{ margin: "0 0 8px", opacity: 0.7 }}>
                Facts Withheld from Reader ({ir.factsWithheld.length})
              </h4>
              <ul style={{ margin: 0, paddingLeft: 20 }}>
                {ir.factsWithheld.map((f, i) => (
                  <li key={i} style={{ opacity: 0.6 }}>
                    {f}
                  </li>
                ))}
              </ul>
            </section>
          )}
        </div>
      )}
    </div>
  );
}
