// src/app/components/SceneSequencer.tsx
import React from "react";
import type { Chunk, SceneStatus } from "../../types/index.js";
import type { SceneEntry, AppAction } from "../hooks/useProject.js";

interface Props {
  scenes: SceneEntry[];
  activeSceneIndex: number;
  sceneChunks: Record<string, Chunk[]>;
  dispatch: React.Dispatch<AppAction>;
}

const STATUS_LABELS: Record<SceneStatus, string> = {
  planned: "PLANNED",
  drafting: "DRAFTING",
  complete: "COMPLETE",
};

const STATUS_CLASSES: Record<SceneStatus, string> = {
  planned: "badge-pending",
  drafting: "badge-edited",
  complete: "badge-accepted",
};

export function SceneSequencer({ scenes, activeSceneIndex, sceneChunks, dispatch }: Props) {
  if (scenes.length === 0) return null;

  return (
    <div className="scene-sequencer">
      {scenes.map((entry, i) => {
        const chunks = sceneChunks[entry.plan.id] ?? [];
        const isActive = i === activeSceneIndex;
        return (
          <button
            key={entry.plan.id}
            className={`scene-card ${isActive ? "scene-card-active" : ""}`}
            onClick={() => dispatch({ type: "SET_ACTIVE_SCENE", index: i })}
          >
            <div className="scene-card-title">
              {entry.plan.title || `Scene ${i + 1}`}
            </div>
            <div className="scene-card-meta">
              <span className={`badge ${STATUS_CLASSES[entry.status]}`}>
                {STATUS_LABELS[entry.status]}
              </span>
              <span className="scene-card-chunks">
                {chunks.length}/{entry.plan.chunkCount}
              </span>
            </div>
          </button>
        );
      })}
    </div>
  );
}

// src/app/components/SceneSequencer.svelte
<script lang="ts">
import type { Chunk, SceneStatus } from "../../types/index.js";
import { Badge } from "../primitives/index.js";
import type { SceneEntry } from "../store/project.svelte.js";

let {
  scenes,
  activeSceneIndex,
  sceneChunks,
  onSelectScene,
}: {
  scenes: SceneEntry[];
  activeSceneIndex: number;
  sceneChunks: Record<string, Chunk[]>;
  onSelectScene: (index: number) => void;
} = $props();

const STATUS_LABELS: Record<SceneStatus, string> = {
  planned: "PLANNED",
  drafting: "DRAFTING",
  complete: "COMPLETE",
};

const STATUS_VARIANTS: Record<SceneStatus, "pending" | "edited" | "accepted"> = {
  planned: "pending",
  drafting: "edited",
  complete: "accepted",
};
</script>

{#if scenes.length > 0}
  <div class="scene-sequencer">
    {#each scenes as entry, i (entry.plan.id)}
      {@const chunks = sceneChunks[entry.plan.id] ?? []}
      <button
        type="button"
        class="scene-card {i === activeSceneIndex ? 'scene-card-active' : ''}"
        onclick={() => onSelectScene(i)}
      >
        <div class="scene-card-title">{entry.plan.title || `Scene ${i + 1}`}</div>
        <div class="scene-card-meta">
          <Badge variant={STATUS_VARIANTS[entry.status]}>{STATUS_LABELS[entry.status]}</Badge>
          <span class="scene-card-chunks">{chunks.length}/{entry.plan.chunkCount}</span>
        </div>
      </button>
    {/each}
  </div>
{/if}

<style>
  .scene-sequencer {
    display: flex; gap: 4px; padding: 6px 8px;
    background: var(--bg-secondary); border-bottom: 1px solid var(--border);
    overflow-x: auto; flex-shrink: 0;
  }
  .scene-card {
    display: flex; flex-direction: column; gap: 4px; padding: 6px 12px;
    background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-md);
    min-width: 120px; text-align: left; cursor: pointer; transition: all 0.15s;
    font-family: var(--font-mono); font-size: inherit; color: inherit;
  }
  .scene-card:hover { border-color: var(--accent-dim); }
  .scene-card-active { border-color: var(--accent); background: rgba(0, 212, 255, 0.08); }
  .scene-card-title {
    font-size: 11px; color: var(--text-primary);
    white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  }
  .scene-card-meta { display: flex; align-items: center; justify-content: space-between; gap: 6px; }
  .scene-card-chunks { font-size: 10px; color: var(--text-muted); }
</style>
